config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  namespace :admin do
    resources :users
  end
  resources :alcohol_logs, only: [:index, :show, :new, :create, :edit, :update]
  resources :paid_leaves, only: [:index, :show] do
    collection do
      # resources :request, only: [:create, :new]
      resources :approval, only: [:create, :new, :edit, :update]
    end
  end
  devise_scope :user do
    get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in', as: 'guest_sign_in'
    get 'admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in', as: 'admin_guest_sign_in'

  end

  root to: 'paid_leaves#index'

 
  # root to: 'paid_leaves#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/approval.rb
class Approval < ApplicationRecord
  belongs_to :user
  belongs_to :paid_leave

  validates :request_date, presence: true
  validates :acquisition_date, presence: true
  validates :paid_applicable, inclusion: { in: [true, false] }
  validates :paid_remarks, length: { maximum: 255 }
end

app/controllers/approval_controller.rb
class ApprovalController < ApplicationController
  def new
    @approval = Approval.new
  end

  def create 
    @paid_leave = current_user.paid_leave
    @approval = @paid_leave.approvals.build(approval_params)
    @approval.user = current_user

    if @approval.save
      redirect_to paid_leafe_path(@paid_leave), notice: "有給休暇の申請が完了しました"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @approval = Approval.find(params[:id])
  end

  def update
    @approval = Approval.find(params[:id])
    if @approval.update(approval_params)
      flash[:notice] = '有給休暇の申請を更新しました'
      redirect_to paid_leafe_path(@approval.paid_leave_id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def approval_params
    params.require(:approval).permit(:request_date, :acquisition_date, :paid_applicable, :paid_remarks)
  end
end

app/views/approval/edit.html.erb
<div class="row">
  <div class="col-8">
  <%= form_with(model: @approval, url: approval_path(@approval), remote: false) do |form| %>
    <% if @approval.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @approval.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <h1><%= t('addition.Editing Paid Leave') %></h1>

    <div>
      <%= form.label :request_date %>
      <%= form.date_field :request_date, class: "form-control" %>
    </div>

    <div>
      <%= form.label :acquisition_date %>
      <%= form.date_field :acquisition_date, class: "form-control" %>
    </div>

    <div>
      <%= form.label :paid_remarks %>
      <%= form.text_area :paid_remarks, class: "form-control", placeholder: "特記事項あれば記入 例）介護休暇" %>
    </div>
    
    <div>
      <%= form.label :paid_applicable %>
      <%= form.check_box :paid_applicable %>
    </div>

    <div>
      <%= form.submit class: "btn btn-outline-primary mt-4" %>
    </div>
  <% end %>
  </div>
</div>

app/views/approval/new.html.erb
<div class="row">
  <div class="col-8">
  <%= form_with(model: @approval, url: approval_index_path, remote: false) do |form| %>
    <% if @approval.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @approval.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <h1><%= t('addition.New paid leave') %></h1>
  
    <div>
      <%= form.label :request_date %>
      <%= form.date_field :request_date, class: "form-control" %>
    </div>

    <div>
      <%= form.label :acquisition_date %>
      <%= form.date_field :acquisition_date, class: "form-control" %>
    </div>

    <div>
      <%= form.label :paid_remarks %>
      <%= form.text_area :paid_remarks, class: "form-control", placeholder: "特記事項あれば記入 例）介護休暇" %>
    </div>

    <div>
      <%= form.submit class: "btn btn-outline-primary mt-4" %>
    </div>
<% end %>

<br>

    <div>
      <%= link_to t('addition.Back'), paid_leaves_path, class: "text-decoration-none" %>
    </div>
  </div>
</div>