config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  namespace :admin do
    resources :users
  end
  resources :alcohol_logs, only: [:index, :show, :new, :create, :edit, :update]
  resources :paid_leaves, only: [:index, :show] do
    collection do
      # resources :request, only: [:create, :new]
      resources :approval, only: [:create, :new, :edit, :update]
    end
  end
  devise_scope :user do
    get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in', as: 'guest_sign_in'
    get 'admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in', as: 'admin_guest_sign_in'

  end

  root to: 'paid_leaves#index'

 
  # root to: 'paid_leaves#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/paid_leave.rb
class PaidLeave < ApplicationRecord
  belongs_to :user

  has_one :grant, dependent: :destroy

  has_many :requests
  accepts_nested_attributes_for :requests, allow_destroy: true 
  
  has_many :approvals
  accepts_nested_attributes_for :approvals, allow_destroy: true 

  validates :joining_date, presence: true
  validates :base_date, presence: true
  validates :part_time, presence: { allow_nil: true, allow_blank: true }
  validates :classification, presence: { allow_nil: true, allow_blank: true }, on: [:create, :update]                      


  enum :classification, {
    "4days_w": 0,
    "3days_w": 1,
    "2days_w": 2,
    "1days_w": 3,
    "others": 4
    }

end

app/controllers/paid_leaves_controller.rb
class PaidLeavesController < ApplicationController
  before_action :set_paid_leave, only: %i[ show ]

  # GET /paid_leaves or /paid_leaves.json
  def index
    @users = User.includes(:paid_leave, :alcohol_logs, :requests, :approvals).all
    @users = @users.order('paid_leaves.id ASC')
    
    @user_service = @users.map do |user|
      approvals = Approval.where(user_id: user.id)
      part_time = user.paid_leave.part_time
      classification = user.paid_leave.classification
      base_date =  user.paid_leave.base_date
      joining_date = user.paid_leave.joining_date
      service = Service.new(user, approvals, part_time, classification, base_date, joining_date)

      {
        user: user,
        discrimination: service.discrimination,
        achievements: service.achievements,
        items: service.items,
        paid_leave: user.paid_leave,
      }
    end
  end
  
  # GET /paid_leaves/1 or /paid_leaves/1.json
  def show
    user = PaidLeave.find(params[:id])
    part_time =  @paid_leave.part_time

    approvals = @paid_leave.approvals
    classification = @paid_leave.classification
    base_date = @paid_leave.base_date
    joining_date = @paid_leave.joining_date

    service = Service.new(user, approvals, part_time, classification, base_date, joining_date)
    @achievements = service.achievements
    @discrimination = service.discrimination
    @total_days = service.total_days
    @items = service.items
    @carry_over = service.carry_over
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paid_leave
      @paid_leave = PaidLeave.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paid_leave_params
      params.require(:paid_leave).permit(:joining_date, :base_date, :part_time, :user_id, :paid_remarks, request_atteibutes: [:request_date, :acquisition_date, :paid_remarks], approve_attributes: [:id, :request_date, :acquisition_date, :paid_remarks])
    end

    def guest_user?
      current_user.email == 'guest@example.com'
    end
end

app/views/paid_leaves/index.html.erb
<h1><%= t('addition.Paid Leaves') %></h1>

<%= I18n.l(Date.today, format: :middle) %>

<table class="table table-striped">
  <thead>
    <tr class="table-primary">
      <th>No</th>
      <th><%= t('addition.Name') %></th>
      <th><%= t('addition.Joining') %></th>
      <th><%= t('addition.Basis') %></th>
      <th><%= t('addition.Possession') %></th>
      <th><%= t('addition.Plan') %></th>
      <th><%= t('addition.Achievements') %></th>
      <% (4..12).each do |month| %>
        <th><%= month %>月</th>
      <% end %>
      <% (1..3).each do |month| %>
        <th><%= month %>月</th>
      <% end %>
      <th></th>
    </tr>
  </thead>

<tbody>
  <% @user_service.each_with_index do |service, index|%>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= service[:user].name %></td>
      <td><%= I18n.l(service[:user].paid_leave.joining_date, format: :middle) %></td>
      <td><%= I18n.l(service[:user].paid_leave.base_date, format: :middle) %></td>
      <td><%= service[:discrimination] %></td>
      <td><%= service[:discrimination] %></td>
      <td id="target"><%= service[:achievements] %></td>

      <% (4..12).each do |month| %>
        <td>
          <%= service[:items][month.to_f] || 0 %>
        </td>
      <% end %>
      
      <% (1..3).each do |month| %>
        <td>
          <%= service[:items][month.to_f] || 0 %>
        </td>
      <% end %>
    
      <td>
        <%= link_to t('addition.Show'), paid_leafe_path(service[:paid_leave].id), class: "btn btn-outline-primary" %>  
      </td>
    </tr>
  <% end %>
</tbody>
</table>

<br>

app/views/paid_leaves/show.html.erb
<h1><%= Date.today.year %><%= t('addition.Paid leaves Show') %></h1>

<p class="text-end text-decoration-underline"><%= t('activerecord.attributes.user.department') %>&nbsp;&nbsp;<%= @paid_leave.user.department_i18n %></p>
<p class="text-end text-decoration-underline"><%= t('activerecord.attributes.user.name') %>&nbsp;&nbsp;<%= @paid_leave.user.name %></p>

<table class="table table-bordered mb-0">
  <tbody>
      <tr>
        <td colspan="2" class="table-primary"><%= t('activerecord.attributes.paid_leave.base_date') %></td>
        <td colspan="4"><%= I18n.l(@paid_leave.base_date, format: :middle) %></td>
      </tr>
      <tr>
        <td colspan="2" class="table-primary"><%= t('addition.Validity Period') %></td>
        <td colspan="4"><%= "#{I18n.l(@paid_leave.base_date, format: :middle)}～#{I18n.l(@paid_leave.base_date.next_year - 1, format: :middle)}" %></td>
      </tr>
      <tr>
        <td ><%= t('addition.Total Days') %></td>
        <td><%= @total_days %></td>

        <td><%= t('addition.Carry Over') %></td>
        <td><%= @carry_over %></td>

        <td><%= t('addition.Granted This Year') %></td>
        <td><%= @discrimination %></td>
      </tr>
  <tbody>
</table>
<table class="table table-striped">
  <thead>
    <tr class="table-primary">
      <th>No</th>
      <th><%= t('addition.Date of notification') %></th>
      <th><%= t('addition.Application Date') %></th>
      <th><%= t('addition.Remaining Days') %></th>
      <th><%= t('addition.Personal Stamp') %></th>
      <th><%= t('addition.Approval Stamp') %></th>
      <th><%= t('addition.Remarks') %></th>
      <th><%= t('addition.Applicable') %></th>
      <% if current_user.admin? %>
        <th></th>
      <% end %>
    </tr>
  </thead>
    
  <tbody>
    <% @paid_leave.approvals.each_with_index do |approval, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= I18n.l(approval.request_date, format: :middle) %></td>
        <td><%= I18n.l(approval.acquisition_date, format: :middle) %></td>
        <td id="target"><%= @total_days %></td>
        <td></td> <!-- 空のセル -->
        <td></td> <!-- 空のセル -->
        <td><%= approval.paid_remarks %></td>
        <td><%= approval.paid_applicable ? '適用' : '未適用' %></td>

        <div>
          <% if current_user.admin? %>
            <td><%= link_to t('addition.Edit'), edit_approval_path(approval.id), class: "btn btn-outline-primary" %></td>
          <% end %>
        </div>
      </tr>      
    <% end %>
  </tbody>
</table>
  
<div>
  <%= link_to t('addition.Back'), paid_leaves_path, class: "text-decoration-none" %>
</div>