config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  namespace :admin do
    resources :users
  end
  resources :alcohol_logs, only: [:index, :show, :new, :create, :edit, :update]
  resources :paid_leaves, only: [:index, :show] do
    collection do
      # resources :request, only: [:create, :new]
      resources :approval, only: [:create, :new, :edit, :update]
    end
  end
  devise_scope :user do
    get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in', as: 'guest_sign_in'
    get 'admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in', as: 'admin_guest_sign_in'

  end

  root to: 'paid_leaves#index'

 
  # root to: 'paid_leaves#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :paid_leave, class_name: 'PaidLeave', dependent: :destroy 
  accepts_nested_attributes_for :paid_leave, allow_destroy: true

  has_many :requests, dependent: :destroy 
  accepts_nested_attributes_for :requests, allow_destroy: true 

  has_one :grant, dependent: :destroy 
  accepts_nested_attributes_for :grant, allow_destroy: true

  has_many :approvals, dependent: :destroy 
  accepts_nested_attributes_for :approvals, allow_destroy: true

  has_one :car, dependent: :destroy 
  accepts_nested_attributes_for :car, allow_destroy: true

  has_many :alcohol_logs, dependent: :destroy 

  validates :name, presence: true
  validates :department, presence: true
  validates :admin, inclusion: { in: [true, false] }

  validates_associated :paid_leave, :car, :grant

  enum :department, {
    sales: 0, 
    air_conditioning: 1,
    manufacturing: 2,
    design: 3,
    management: 4,
    others: 5
    }

  def user_validate
    return unless user.invalid?
      user.errors.full_messages.each do |message|
      errors.add(:base, message)
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/admin/users_controller.rb
  class Admin::UsersController < ApplicationController
    before_action :admin?
    before_action :set_user, only: %i[ show edit update destroy ]

    # GET /users or /users.json
    def index
      @users = User.includes(:car, :paid_leave).all
      @users = @users.order('paid_leaves.joining_date ASC')
      @cars = Car.all
      @paid_leaves = PaidLeave.all
    end

    # GET /users/1 or /users/1.json
    def show
    end

    # GET /users/new
    def new
      @user = User.new
      @user.build_car
      @user.build_paid_leave
      @user.build_grant
    end

    # POST /users or /users.json
    def create
      ActiveRecord::Base.transaction do
        @user = User.new(user_params)
        @paid_leave = @user.build_paid_leave(paid_leave_params)
        @grant = @paid_leave.build_grant(grant_params)
        @grant.user = @user
        @car = @user.build_car(car_params)
        
        if @user.save
          flash[:notice] = "社員情報の登録が完了しました"
          redirect_to admin_users_path
        else
        render :new, status: :unprocessable_entity
        end
      end
      rescue ActiveRecord::Rollback => e
      flash[:danger] = "Error: #{e.message}"            
    end

    # GET /users/1/edit
    def edit
      @user = User.find(params[:id])
      @paid_leave = @user.paid_leave
      @car = @user.car
      @grant = @user.grant

      user = User.all
      part_time = PaidLeave.find_by(user_id: user.ids).part_time
      base_date = PaidLeave.find_by(user_id: user.ids).base_date
      joining_date = PaidLeave.find_by(user_id: user.ids).joining_date
      approvals = Approval.all
      classification = PaidLeave.pluck(:classification)
      adjustment_value = params[:adjustment_value].to_i
      adjustment_plan_value = params[:adjustment_plan_value].to_i
      adjustment_carry_value = params[:adjustment_carry_value].to_i

      service = Service.new(user, approvals, adjustment_value, classification, base_date, joining_date)
      @discrimination = service.discrimination
      @carry_over = service.carry_over
      @total_days = service.total_days
      @adjusted_total_days = service.adjusted_total_days
      @adjusted_plan = service.adjusted_plan
      @adjusted_carry_over = service.adjusted_carry_over
    end

    # PATCH/PUT /users/1 or /users/1.json
    def update
      @user = User.find(params[:id])
      @paid_leave = @user.paid_leave
      @car = @user.car
      @grant = @user.grant

      if @user.update(user_params) && @paid_leave.update(paid_leave_params) && @car.update(car_params) && @grant.update(grant_params)
        redirect_to admin_users_path, notice: "社員情報の更新が完了しました"
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /users/1 or /users/1.json
    def destroy
      if @user.destroy
        flash[:notice] = '社員情報の削除が完了しました'
        redirect_to admin_users_path, status: :see_other
      else
        flash[:danger] = @user.errors.full_messages.to_sentence
        redirect_to admin_user_path(@user), status: :unprocessable_entity
      end
    end

    def guest_sign_in
      user = User.find_or_create_by!(email: 'guest@example.com') do |user|
        user.password = SecureRandom.urlsafe_base64
      end
      sign_in user
      redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :department, :admin, :password, :password_confirmation)
    end

    def paid_leave_params
      params.require(:paid_leave).permit(:joining_date, :base_date, :part_time, :classification)
    end

    def car_params
      params.require(:car).permit(:company_car, :private_car)
    end

    def grant_params
      params.require(:grant).permit(:granted_piece, :granted_day)
    end

    def admin?
      unless current_user.admin?
        flash[:danger] = "管理者以外アクセスできません"
        redirect_to paid_leaves_path
      end
    end
  end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.find_or_create_by(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'ゲストユーザー' 
      user.department = 5
      user.admin = false
    end
    user.create_paid_leave(
      joining_date: Date.today,
      base_date: Date.today,    
      part_time: false,        
      classification: 4         
    )
    user.create_car(private_car: "", company_car: "下関111あ1111")
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def admin_guest_sign_in
    user = User.find_or_create_by(email: 'guest_admin@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = '管理者ゲストユーザー'
      user.department = 5
      user.admin = true 
    end
    user.create_paid_leave(
      joining_date: Date.today,
      base_date: Date.today,    
      part_time: false,        
      classification: 4         
    )
    user.create_car(private_car: "", company_car: "下関111あ1111")
    sign_in user
    redirect_to root_path, notice: '管理者ゲストユーザーとしてログインしました。'
  end
end

app/views/admin/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<h2>basic information</h2>

<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :department %>
    <%= form.select :department, @user.class.departments.keys, { include_blank: true } %>
  </div>

  <div>
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>
<% end %>

<%= form.fields_for :paid_leaves do |paid_leaves_form| %>
  <div>
    <%= paid_leaves_form.label :joining_date %>
    <%= paid_leaves_form.date_field :joining_date %>
  </div>

  <div>
      <%= paid_leaves_form.label :part_time %>
      <%= paid_leaves_form.check_box :part_time, {checked: false}, true, false  %>
  </div>

  <div>
    <%= paid_leaves_form.label :classification %>
    <%= paid_leaves_form.select :classification, @paid_leave.class.classifications.keys, { include_blank: true } %>
  </div>
<% end %>

<%= form.fields_for :cars do |cars_form| %>
  <div>
    <%= cars_form.label :company_car %>
    <%= cars_form.text_field :company_car %>
  </div>

  <div>
    <%= cars_form.label :private_car %>
    <%= cars_form.text_field :private_car %>
  </div>
<% end %>

<h2>paid leave information</h2>

<%= form.fields_for :paid_leaves do |paid_leaves_form| %>
  <div>
    <%= paid_leaves_form.label :base_date %>
    <%= paid_leaves_form.date_field :base_date %>
  </div>

  <div>
    <%= paid_leaves_form.label :possession %>
    <%= paid_leaves_form.text_field :possession %>
  </div>

  <div>
  <%= paid_leaves_form.label :granted_piece %> <!-- scheduled days -->
  <%= paid_leaves_form.text_field :granted_piece %> # scheduled days
  </div>

  <div>
  <%= paid_leaves_form.label :granted_piece %> <!-- carry over -->
  <%= paid_leaves_form.text_field :granted_piece %> # carry over
  </div>

  <div>
  <%= paid_leaves_form.label :granted_piece %>
  <%= paid_leaves_form.text_field :granted_piece %>
  </div>
<% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-8">
  <%= form_with model: [:admin, @user], url: admin_user_path(@user), remote: false do |form| %>  
    <% if @user.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% if @paid_leave.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @paid_leave.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% if @car.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @car.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% if @grant.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @grant.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <h1><%= t('addition.Editing user') %></h1>

  <h2><%= t('addition.basic information') %></h2>

  <%= fields_for @user do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div>
     <%= form.label :email %>
     <%= form.text_field :email, class: "form-control" %>
    </div>

    <div>
      <%= form.label :department %>
      <%= form.select :department, User.departments.keys.map {|k| [I18n.t("enums.user.department.#{k}"), k]}, { include_blank: true }, class: "form-control" %>
    </div>

    <div>
      <%= form.label :admin %>
      <%= form.check_box :admin %>
    </div>

    <div>
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control" %>
    </div>

    <div>
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>
  <% end %>

  <%= fields_for form.object.car do |form| %>
    <div>
      <%= form.label :company_car %>
      <%= form.text_field :company_car, class: "form-control" %>
    </div>

    <div>
      <%= form.label :private_car %>
      <%= form.text_field :private_car, class: "form-control" %>
    </div>
  <% end %>

  <h2><%= t('addition.paid leave information') %></h2>

  <%= fields_for form.object.paid_leave do |form| %>
    <div>
      <%= form.label :joining_date %>
      <%= form.date_field :joining_date, class: "form-control" %>
    </div>

    <div>
      <%= form.label :base_date %>
      <%= form.date_field :base_date, class: "form-control" %>
    </div>

    <div>
      <%= form.label :part_time %>
      <%= form.check_box :part_time, {checked: false}, true, false  %>
    </div>

    <div>
      <%= form.label :classification %>
      <%= form.select :classification, PaidLeave.classifications.keys.map {|k| [I18n.t("enums.paid_leave.classification.#{k}"), k]}, { include_blank: true }, class: "form-control" %>
    </div>
  <% end %>

  <%= fields_for form.object.grant do |form| %>
    <div>
      <%= form.label :granted_piece, "有給付与予定数" %>
      <%= form.number_field :granted_piece, min: 0, class: "form-control" %>
    </div>

    <div>
      <%= form.label :granted_day, "有給付与予定日" %>
      <%= form.date_field :granted_day, class: "form-control" %>
    </div>
  <% end %>

    <div>
      <%= form.submit class: "btn btn-outline-primary mt-4" %>
    </div>
  <% end %>

  <div>
    <%= link_to t('addition.Back'), admin_users_path %>
  </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<h1><%= t('addition.Users') %></h1>

<table class="table table-striped">
  <tbody>
    <tr class="table-primary">
      <td><%= t('activerecord.attributes.user.name') %></td>
      <td><%= t('activerecord.attributes.user.department') %></td>
      <td><%= t('activerecord.attributes.user.email') %></td>
      <td><%= t('activerecord.attributes.alcohol_log.car_id') %></td>
      <td><%= t('activerecord.attributes.paid_leave.joining_date') %></td>
      <td></td>
    </tr>

    <tr>
    <% @users.each do |user| %>
      <td><%= user.name %></td>
      <td><%= user.department_i18n %></td>
      <td><%= user.email %></td>
      <td><%= user.car.private_car&.presence || user.car.company_car %></td>
      <td>
        <%= I18n.l(user.paid_leave.joining_date, format: :middle) %>
      </td>
    
      <td>
        <div>
          <%= link_to t('addition.Edit'), edit_admin_user_path(user), class: "btn btn-outline-primary btn-sm mb-1" %>
          <%= button_to t('addition.Destroy'), admin_user_path(user), method: :delete, data: { turbo_method: :get, turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
        </div>
      </td> 
    </tr>
    <% end %>
  <tbody>
</table>

app/views/admin/users/new.html.erb
<div class="row">
  <div class="col-8">
  <%= form_with model: [:admin, @user], remote: false do |form| %>
    <% if @user.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <h1><%= t('addition.New user') %></h1>
  
  <h2><%= t('addition.basic information') %></h2>

  <%= fields_for @user do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control", placeholder: "例）〇〇 〇〇" %>
    </div>

    <div>
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control", placeholder: "例）aa@example.com" %>
    </div>
  
    <div>
      <%= form.label :department %>
      <%= form.select :department, User.departments.keys.map {|k| [I18n.t("enums.user.department.#{k}"), k]}, { include_blank: true }, class: "form-control" %>
    </div>

    <div>
      <%= form.label :admin %>
      <%= form.check_box :detector_used, {checked: false}, true, false  %>
    </div>

    <div>
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control" %>
    </div>

    <div>
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>
  <% end %>

  <%= fields_for form.object.car do |form| %>
    <div>
      <%= form.label :company_car %>
      <%= form.text_field :company_car, class: "form-control", placeholder: "例)下関111あ1111" %>
    </div>

    <div>
      <%= form.label :private_car %>
      <%= form.text_field :private_car, class: "form-control", placeholder: "例)下関111あ1111" %>
    </div>
  <% end %>

  <h2><%= t('addition.paid leave information') %></h2>

  <%= fields_for form.object.paid_leave do |form| %>
    <div>
      <%= form.label :joining_date %>
      <%= form.date_field :joining_date, class: "form-control" %>
    </div>

    <div>
      <%= form.label :base_date %>
      <%= form.date_field :base_date, class: "form-control" %>
    </div>
    
    <div>
      <%= form.label :part_time %>
      <%= form.check_box :part_time, {checked: false}, true, false  %>
    </div>

    <div>
      <%= form.label :classification %>
      <%= form.select :classification, PaidLeave.classifications.keys.map {|k| [I18n.t("enums.paid_leave.classification.#{k}"), k]}, { include_blank: true }, class: "form-control" %>
    </div>
  <% end %>

  <%= fields_for form.object.grant do |form| %>
    <div>
      <%= form.label :granted_piece %>
      <%= form.number_field :granted_piece, min: 0, class: "form-control" %>
    </div>

    <div>
      <%= form.label :granted_day %>
      <%= form.date_field :granted_day, class: "form-control" %>
    </div>
  <% end %>

  <div>
    <%= form.submit class: "btn btn-outline-primary mt-4" %>
  </div>
  <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>